server:
  port: 7002


################################## Eureka 单机版配置 ############################################
#eureka:
#  instance:
#    hostname: localhost   # eureka 服务端的实例名称
#  client:
#    # false 表示不向注册中心注册自己
#    register-with-eureka: false
#    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
#    fetch-registry: false
#    service-url:
#      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
################################## Eureka 单机版配置 ############################################


################################## Eureka 集群配置 ############################################
eureka:
  instance:
    hostname: eureka7002.com   # eureka 服务端的实例名称
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 集群配置的多个服务器相互注册，互相守望
      defaultZone: http://eureka7001.com:7001/eureka/
################################## Eureka 集群配置 ############################################
