server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh  #payment_route  #路由的 ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          filters:
            - AddRequestHeader=X-Request-red, blue
            - AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/payment/lb/**
#            - After=2020-08-07T10:43:31.255+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id, \d+  #请求头要有 X-Request-Id 属性并且值为整数的正则表达式
#            - Host=**.jason.org
#            - Method=GET
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

