server:
  port: 7001


################################## Eureka 单机版配置 ############################################
#eureka:
#  instance:
#    hostname: localhost   # eureka 服务端的实例名称
#  client:
#    # false 表示不向注册中心注册自己
#    register-with-eureka: false
#    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
#    fetch-registry: false
#    service-url:
#      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
################################## Eureka 单机版配置 ############################################


################################## Eureka 集群配置 ############################################
eureka:
  instance:
    hostname: eureka7001.com   # eureka 服务端的实例名称
  client:
    # false 表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
#  server:
#    # 关闭自我保护机制，保证不可用服务被及时剔除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000 # 2000毫秒
################################## Eureka 集群配置 ############################################